### PR TITLE
Fix auth_app for modern Taiga versions (#227)

### LINKED ISSUE #189: Can not install the lib: pyjwkest-1.4.2
## Description
I wanna install the taiga in my python environment(3.10)，However,
 

## Steps to reproduce
pip install python_taiga-1.3.0-py2.py3-none-any.whl

or

pip install pip install python-taiga

## Versions

Python version: 3.10
Operating System: [Your OS (e.g., Ubuntu 20.04, macOS, etc.)]
Virtual Environment: Yes
python-taiga version: 1.3.0

## Actual behaviour
```

WARNING: Ignoring invalid distribution -ip (/home/bd8090/Documents/airflow/airflow_env/lib/python3.10/site-packages)
Processing ./python_taiga-1.3.0-py2.py3-none-any.whl
Requirement already satisfied: requests>2.11 in /home/bd8090/Documents/airflow/airflow_env/lib/python3.10/site-packages (from python-taiga==1.3.0) (2.28.1)
Requirement already satisfied: six>=1.9 in /home/bd8090/Documents/airflow/airflow_env/lib/python3.10/site-packages (from python-taiga==1.3.0) (1.16.0)
Requirement already satisfied: python-dateutil>=2.4 in /home/bd8090/Documents/airflow/airflow_env/lib/python3.10/site-packages (from python-taiga==1.3.0) (2.8.2)
Collecting pyjwkest>=1.0 (from python-taiga==1.3.0)
  Using cached pyjwkest-1.4.2.tar.gz (41 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [44 lines of output]
      /home/bd8090/Documents/airflow/airflow_env/lib/python3.10/site-packages/setuptools/_distutils/dist.py:261: UserWarning: Unknown distribution option: 'tests_require'
        warnings.warn(msg)
      running egg_info
      creating /tmp/pip-pip-egg-info-7_xnykoc/pyjwkest.egg-info
      writing /tmp/pip-pip-egg-info-7_xnykoc/pyjwkest.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-pip-egg-info-7_xnykoc/pyjwkest.egg-info/dependency_links.txt
      writing requirements to /tmp/pip-pip-egg-info-7_xnykoc/pyjwkest.egg-info/requires.txt
      writing top-level names to /tmp/pip-pip-egg-info-7_xnykoc/pyjwkest.egg-info/top_level.txt
      writing manifest file '/tmp/pip-pip-egg-info-7_xnykoc/pyjwkest.egg-info/SOURCES.txt'
      [12/02/24 10:24:16] ERROR    listing git files failed - pretending     git.py:26
                                   there aren't any
      reading manifest file '/tmp/pip-pip-egg-info-7_xnykoc/pyjwkest.egg-info/SOURCES.txt'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-kyqctiud/pyjwkest_2c675ed9fe644409acb1b09beecf9ea5/setup.py", line 29, in <module>
          setup(
        File "/home/bd8090/Documents/airflow/airflow_env/lib/python3.10/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
        File "/home/bd8090/Documents/airflow/airflow_env/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
        File "/home/bd8090/Documents/airflow/airflow_env/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
        File "/home/bd8090/Documents/airflow/airflow_env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "/home/bd8090/Documents/airflow/airflow_env/lib/python3.10/site-packages/setuptools/dist.py", line 995, in run_command
          super().run_command(command)
        File "/home/bd8090/Documents/airflow/airflow_env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/home/bd8090/Documents/airflow/airflow_env/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 313, in run
          self.find_sources()
        File "/home/bd8090/Documents/airflow/airflow_env/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 321, in find_sources
          mm.run()
        File "/home/bd8090/Documents/airflow/airflow_env/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 549, in run
          self.prune_file_list()
        File "/home/bd8090/Documents/airflow/airflow_env/lib/python3.10/site-packages/setuptools/command/sdist.py", line 162, in prune_file_list
          super().prune_file_list()
        File "/home/bd8090/Documents/airflow/airflow_env/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 380, in prune_file_list
          base_dir = self.distribution.get_fullname()
        File "/home/bd8090/Documents/airflow/airflow_env/lib/python3.10/site-packages/setuptools/_core_metadata.py", line 267, in get_fullname
          return _distribution_fullname(self.get_name(), self.get_version())
        File "/home/bd8090/Documents/airflow/airflow_env/lib/python3.10/site-packages/setuptools/_core_metadata.py", line 285, in _distribution_fullname
          canonicalize_version(version, strip_trailing_zero=False),
      TypeError: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

## Additional information

it sounds like pyjwkest has problem to install here

### LINKED ISSUE #227: auth_app function outdated
Hi,

The client function `auth_app` is relying on functionality that Taiga hasn't exposed since v3.1.0 in 2016. Application secrets and cyphered tokens were removed in that version of Taiga - the response simply contains a plain `token` field now.

This came up because I was looking at usages of the dependency `pyjwkest`, which is unmaintained. It has a transitive dependency on `future`, which in turn has an unpatched [high severity vulnerability](https://github.com/advisories/GHSA-xqrq-4mgf-ff32) that tripped our pip auditing CI.

I can offer to work on a PR for this, if you'd like.

### PR DESCRIPTION
**Pull request by meck-gd**
# Description

* Fix `auth_app()` to (only) work with Taiga 3.1.0+ (released in 2016).
* The method returns the token now instead of setting it up in the API client. This is because it's not really meant to be used like `auth()` - rather, it only works once per token because the Taiga backend invalidates the `auth_code` during the request. From what I can tell, applications are supposed to store and re-use the token. It doesn't have an expiration, unlike Bearer tokens.
* Dependency pyjwkest is no longer required.

## References

Fixes #227
Due to removal of dependency, also fixes #189

# Checklist

* [x] I have read the [contribution guide](https://python-taiga.readthedocs.io/en/latest/contributing.html)
* [x] Code lint checked via `inv lint`
* [x] ``changes`` file included (see [docs](https://python-taiga.readthedocs.io/en/latest/contributing.html#pull-request-guidelines))
* [ ] Usage documentation added in case of new features
* [ ] Tests added

### CODE REVIEW

File: taiga/client.py [hunk 1]
```diff
@@ -180,31 +186,12 @@ def auth_app(self, app_id, app_secret, auth_code, state=""):
...
-        if self.token is None:
+        token = response.json().get("token", None)
+
+        if token is None:
             raise exceptions.TaigaRestException(full_url, 400, "INVALID TOKEN", "POST")
 
-        self.raw_request = RequestMaker(
-            "/api/v1", self.host, self.token, "Application", self.tls_verify, proxies=self.proxies
-        )
-        self._init_resources()
```
Comment (protoroto) [inline taiga/client.py:207]: @heck-gd Why dropping this? Shouldn't `auth_app` not return anything, and just set `self.raw_request` and `self._init_resources()` as before, but with the new token?

File: tests/test_auth_app.py [hunk 2]
```diff
@@ -14,8 +14,8 @@ class TestAuthApp(unittest.TestCase):
     def test_auth_success(self, requests):
         requests.post.return_value = MockResponse(200, create_mock_json("tests/resources/auth_app_success.json"))
         api = TaigaAPI(host="host")
-        api.auth_app("valid-app-id", "valid-app-secret", "valid-auth-code", "valid-state")
-        self.assertEqual(api.token, "f4k3")
```
Comment (protoroto) [inline tests/test_auth_app.py:18]: @heck-gd Same as above: shouldn't we check that `api.token` is correct after doing `api.auth_app`?

**Review by yakky — APPROVED** [review]
Due to the incompatible signature of auth_app we should release this with a major version bump and documenting the breaking change in the documentation

**Comment by yakky** [comment]
Thanks again for the fix and for the patience while this sat! I rebased your commit onto current master and packaged it as a breaking change (major version bump left to the release process, changelog fragment reclassified, docs added, missing-token branch covered by a test) in #269, which supersedes this PR. Your commit and AUTHORS entry are preserved as-is — closing this in favor of #269.
